-- Catalog schema, initial version.
--
-- SQL here is deliberately vendor-neutral (PLAN.md section 4): plain VARCHAR,
-- NUMERIC, TIMESTAMP, and standard IDENTITY syntax that H2, PostgreSQL and Oracle
-- all accept. That is what keeps a later move off H2 to a one-day job.

CREATE TABLE categories (
    id        BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id VARCHAR(36)  NOT NULL,
    name      VARCHAR(120) NOT NULL,
    slug      VARCHAR(140) NOT NULL,
    CONSTRAINT uq_categories_public_id UNIQUE (public_id),
    CONSTRAINT uq_categories_slug      UNIQUE (slug)
);

CREATE TABLE products (
    id          BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Internal id stays internal. public_id is what appears in URLs and what any
    -- other service would reference, so sequential ids are never leaked.
    public_id   VARCHAR(36)   NOT NULL,

    sku         VARCHAR(64)   NOT NULL,
    name        VARCHAR(200)  NOT NULL,
    description VARCHAR(4000),

    -- Money is NUMERIC(19,4) -> BigDecimal. Never a floating-point type.
    price       NUMERIC(19,4) NOT NULL,

    category_id BIGINT        NOT NULL,
    image_url   VARCHAR(500),
    active      BOOLEAN       NOT NULL DEFAULT TRUE,

    -- UTC, always. Mapped to java.time.Instant.
    created_at  TIMESTAMP     NOT NULL,

    -- Optimistic locking (@Version). Portable across every database, unlike
    -- SELECT ... FOR UPDATE semantics.
    version     INTEGER       NOT NULL DEFAULT 0,

    CONSTRAINT uq_products_public_id UNIQUE (public_id),
    CONSTRAINT uq_products_sku       UNIQUE (sku),
    CONSTRAINT fk_products_category  FOREIGN KEY (category_id) REFERENCES categories (id)
);

CREATE INDEX ix_products_category ON products (category_id);
CREATE INDEX ix_products_active   ON products (active);
