-- Cart schema, initial version.
--
-- Carts are short-lived, mutable scratchpads, not records. Nothing here is an audit
-- trail: once checkout completes, order-service copies what it needs and these rows
-- become disposable.

CREATE TABLE carts (
    id               BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id        VARCHAR(36)  NOT NULL,

    -- Keycloak's `sub` for a signed-in shopper. Null while browsing anonymously.
    customer_id      VARCHAR(36),

    -- An opaque token the SPA holds instead, when nobody is signed in yet.
    anonymous_token  VARCHAR(64),

    status           VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    currency         VARCHAR(3)   NOT NULL DEFAULT 'USD',

    created_at       TIMESTAMP    NOT NULL,
    updated_at       TIMESTAMP    NOT NULL,
    expires_at       TIMESTAMP    NOT NULL,
    version          INTEGER      NOT NULL DEFAULT 0,

    CONSTRAINT uq_carts_public_id UNIQUE (public_id),

    -- A cart belongs to exactly one of the two, never both and never neither.
    -- Expressing it as a CHECK means no application bug can create an orphan cart
    -- or one with two owners.
    CONSTRAINT ck_carts_one_owner CHECK (
        (customer_id IS NOT NULL AND anonymous_token IS NULL)
        OR (customer_id IS NULL AND anonymous_token IS NOT NULL)
    )
);

-- Lookup paths: by owner, and by the expiry sweep.
CREATE INDEX ix_carts_customer  ON carts (customer_id, status);
CREATE INDEX ix_carts_anonymous ON carts (anonymous_token, status);
CREATE INDEX ix_carts_expiry    ON carts (status, expires_at);

CREATE TABLE cart_items (
    id            BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- ON DELETE CASCADE: emptying or expiring a cart takes its lines with it. The
    -- lines have no meaning apart from their cart.
    cart_id       BIGINT        NOT NULL,

    -- The product's public_id, as a plain string. Deliberately NOT a foreign key -
    -- products live in another service's database, which this one cannot reach.
    product_id    VARCHAR(36)   NOT NULL,
    sku           VARCHAR(64)   NOT NULL,

    -- Snapshots, so rendering a cart needs no call to catalog-service. Re-validated
    -- at checkout rather than trusted indefinitely; see POST /api/cart/validate.
    product_name  VARCHAR(200)  NOT NULL,
    unit_price    NUMERIC(19,4) NOT NULL,
    image_url     VARCHAR(500),

    quantity      INTEGER       NOT NULL,
    added_at      TIMESTAMP     NOT NULL,

    CONSTRAINT fk_cart_items_cart FOREIGN KEY (cart_id) REFERENCES carts (id) ON DELETE CASCADE,

    -- Adding a product already in the cart increments its quantity rather than
    -- creating a second line. The constraint is what guarantees that.
    CONSTRAINT uq_cart_items_product UNIQUE (cart_id, product_id),

    CONSTRAINT ck_cart_items_quantity CHECK (quantity > 0)
);

CREATE INDEX ix_cart_items_cart ON cart_items (cart_id);
