import { HttpErrorResponse, HttpInterceptorFn } from '@angular/common/http';
import { catchError, throwError } from 'rxjs';
import { ApiError } from './models/api-error';

/** Error carrying the fields a UI actually needs to show something useful. */
export class ApiRequestError extends Error {
  constructor(
    message: string,
    readonly status: number,
    readonly correlationId: string | null,
  ) {
    super(message);
    this.name = 'ApiRequestError';
  }
}

const SERVICE_UNREACHABLE = 'Cannot reach the API. Is catalog-service running on port 8082?';

/**
 * Narrows an unknown error body to our shared ApiError.
 *
 * Needed because a 5xx does not guarantee the body came from our code. When the
 * service is down, the response is generated by whatever sits in front of it - the
 * Angular dev-server proxy in development, the gateway later - and looks nothing
 * like an ApiError.
 */
function isApiError(body: unknown): body is ApiError {
  if (body === null || typeof body !== 'object') {
    return false;
  }
  const candidate = body as Partial<ApiError>;
  return typeof candidate.message === 'string' && typeof candidate.status === 'number';
}

/**
 * Turns transport-level failures into one predictable error type.
 *
 * Three jobs worth doing here rather than in every component:
 *
 * 1. Read the shared ApiError body when the backend actually sent one, so the user
 *    sees the server's message rather than "Http failure response for /api/...".
 * 2. Recognise when no service answered at all, and say so in a way that names the
 *    likely cause instead of leaking a raw URL into the UI.
 * 3. Keep the correlation ID. When something breaks, that ID is what ties the
 *    message on screen to the matching line in the service logs - which in a
 *    microservices system is the difference between debugging and guessing.
 */
export const httpErrorInterceptor: HttpInterceptorFn = (req, next) =>
  next(req).pipe(
    catchError((response: HttpErrorResponse) => {
      // status 0: the request never got a response at all - network dropped, or
      // CORS blocked it before any status was assigned.
      if (response.status === 0) {
        return throwError(() => new ApiRequestError(SERVICE_UNREACHABLE, 0, null));
      }

      const body = response.error;

      if (isApiError(body)) {
        if (body.correlationId) {
          console.error(
            `API error [correlationId=${body.correlationId}]`,
            body.status,
            body.message,
          );
        }
        return throwError(
          () => new ApiRequestError(body.message, response.status, body.correlationId ?? null),
        );
      }

      // A 5xx with no ApiError body means nothing of ours produced this response.
      // In dev that is the proxy reporting it could not reach port 8082 - which it
      // does as a 500, not a 0, so this branch is what actually catches a stopped
      // backend.
      if (response.status >= 500) {
        console.error(`No ApiError body on HTTP ${response.status} - upstream service likely down`);
        return throwError(() => new ApiRequestError(SERVICE_UNREACHABLE, response.status, null));
      }

      return throwError(
        () =>
          new ApiRequestError(
            `The API returned an unexpected response (HTTP ${response.status}).`,
            response.status,
            null,
          ),
      );
    }),
  );
