-- Customer schema, initial version.
--
-- Vendor-neutral SQL (PLAN.md section 4): plain VARCHAR, TIMESTAMP, and standard
-- IDENTITY syntax that H2, PostgreSQL and Oracle all accept.
--
-- Note what is NOT here: no password hash, no roles table, no tokens. Keycloak owns
-- identity entirely; this service owns only the domain's view of a customer.

CREATE TABLE customers (
    id               BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- What appears in URLs and crosses service boundaries. Internal ids stay internal.
    public_id        VARCHAR(36)  NOT NULL,

    -- Keycloak's `sub` claim: the stable link between this row and the identity
    -- provider. VARCHAR rather than a UUID type because OIDC defines `sub` as an
    -- opaque string - Keycloak's happens to look like a UUID, but nothing guarantees
    -- that across federation or a different IdP.
    keycloak_id      VARCHAR(36)  NOT NULL,

    -- Denormalized copy of the Keycloak email, refreshed from token claims. Present
    -- for display and admin search only - never used as a key, because users can
    -- change their email in Keycloak's account console.
    email            VARCHAR(320) NOT NULL,

    first_name       VARCHAR(100),
    last_name        VARCHAR(100),
    phone            VARCHAR(40),

    marketing_opt_in BOOLEAN      NOT NULL DEFAULT FALSE,
    loyalty_tier     VARCHAR(20)  NOT NULL DEFAULT 'STANDARD',

    -- UTC, always. Mapped to java.time.Instant.
    created_at       TIMESTAMP    NOT NULL,
    updated_at       TIMESTAMP    NOT NULL,

    -- Optimistic locking (@Version).
    version          INTEGER      NOT NULL DEFAULT 0,

    CONSTRAINT uq_customers_public_id   UNIQUE (public_id),

    -- This constraint is load-bearing: it is what makes just-in-time provisioning
    -- safe. Two simultaneous first requests can both see "no such customer" and both
    -- try to insert; the database rejects the loser and the service re-reads.
    CONSTRAINT uq_customers_keycloak_id UNIQUE (keycloak_id)
);

CREATE INDEX ix_customers_email ON customers (email);

CREATE TABLE addresses (
    id                  BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id           VARCHAR(36)  NOT NULL,
    customer_id         BIGINT       NOT NULL,

    label               VARCHAR(60),
    recipient_name      VARCHAR(200) NOT NULL,
    line1               VARCHAR(200) NOT NULL,
    line2               VARCHAR(200),
    city                VARCHAR(120) NOT NULL,
    region              VARCHAR(120),
    postal_code         VARCHAR(20)  NOT NULL,

    -- ISO 3166-1 alpha-2. VARCHAR(2) rather than CHAR(2) on purpose: Hibernate maps
    -- String to VARCHAR, and ddl-auto: validate compares the declared types, so a
    -- CHAR column would fail validation at startup.
    country_code        VARCHAR(2)   NOT NULL,

    phone               VARCHAR(40),

    is_default_shipping BOOLEAN      NOT NULL DEFAULT FALSE,
    is_default_billing  BOOLEAN      NOT NULL DEFAULT FALSE,

    created_at          TIMESTAMP    NOT NULL,
    version             INTEGER      NOT NULL DEFAULT 0,

    CONSTRAINT uq_addresses_public_id UNIQUE (public_id),
    CONSTRAINT fk_addresses_customer  FOREIGN KEY (customer_id) REFERENCES customers (id)
);

CREATE INDEX ix_addresses_customer ON addresses (customer_id);
